### ISSUE TITLE
Error while lauching my app

### ISSUE THREAD

**Issue by Pacane** [talsec/Free-RASP-Flutter#6] opened 2021-12-10 21:37 UTC
I've trying to run my app using freerasp and when it's launched I get this error at runtime:

```
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.aheaditec.com/events:
MissingPluginException(No implementation found for method listen on channel plugins.aheaditec.com/events)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506:9)
<asynchronous suspension>
```

When I remove this line
`TalsecApp(callback: callback, config: talsecConfig).start();`

It's not throwing it anymore.

I have a dependency on freerasp: ^1.1.0

Have you experienced something alike in the past?

**Comment by talsec-app** [comment] 2021-12-14 10:07
Thank you for your submission, we will try to reproduce this issue and get back to you with solution.

**Comment by talsec-app** [comment] 2022-01-21 13:58
Hello.
To be able to precisely pinpoint the problem, we need to ask for further details:
Does it happen on simulator/emulator or real device (or both)?
Does it happen on Android or iOS or both?
Does it happen on dev or release or both?

**Comment by urbanjagodic** [comment] 2022-01-24 09:19
Same issue here. 

Tried it with a physical android device (OS 11) and an android emulator, but the issue persists.
Both happen in a debug build mode.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Ubuntu 20.04.3 LTS 5.13.0-27-generic,)

**Comment by lcuis** [comment] 2022-01-26 21:21
I get the same issue with the following message:
```
E/MethodChannel#plugins.aheaditec.com/config(20612): Failed to handle method call
E/MethodChannel#plugins.aheaditec.com/config(20612): java.lang.NullPointerException
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at com.aheaditec.freerasp.FreeraspPlugin.onMethodCall(FreeraspPlugin.kt:29)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at android.app.ActivityThread.main(ActivityThread.java:8595)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#plugins.aheaditec.com/config(20612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (20612): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (20612): 	at com.aheaditec.freerasp.FreeraspPlugin.onMethodCall(FreeraspPlugin.kt:29)
E/flutter (20612): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (20612): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (20612): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (20612): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (20612): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (20612): 	at android.os.Looper.loop(Looper.java:206)
E/flutter (20612): 	at android.app.ActivityThread.main(ActivityThread.java:8595)
E/flutter (20612): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20612): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (20612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (20612): )
E/flutter (20612): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (20612): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (20612): <asynchronous suspension>
E/flutter (20612): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:35)
E/flutter (20612): <asynchronous suspension>
E/flutter (20612): 

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel plugins.aheaditec.com/events:
MissingPluginException(No implementation found for method listen on channel plugins.aheaditec.com/events)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
====================================================================================================
```

I followed [these instructions](https://github.com/talsec/Free-RASP-Android/issues/2), but this did not change the outcome:

I get this in release and debug on a physical device using android 11.

**Comment by lcuis** [comment] 2022-01-26 22:42
This issue does not happen for me on a new blank flutter app.

**Comment by lcuis** [comment] 2022-01-27 05:45
Here is the content of my `android/gradle/wrapper/gradle-wrapper.properties` file for the failing project:
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
```

For the working project:
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```

The `android/buid.gradle` files are aligned in both projects:
```
buildscript {
    ext.kotlin_version = '1.5.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {url "[https://nexus3-public.monetplus.cz/repository/ahead-talsec-free-rasp]" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

I aligned the `android/app/build.gradle` files except for the `compileSdkVersion`:
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.trying_rasp"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
//    releaseImplementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:3.1.0-release'
//    debugImplementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:3.1.0-dev'
//    implementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:3.1.0-dev'
    implementation 'com.aheaditec.talsec.security:TalsecSecurity-Community:3.1.0-release'
}
```

Here is why I had to keep `compileSdkVersion 31` in my original project:
```
Launching lib/main.dart on SM A037F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
     AAR metadata file: /home/x/.gradle/caches/transforms-2/files-2.1/502c2f840b10fb1c326115a8cffd99c6/work-runtime-2.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Exception: Gradle task assembleDebug failed with exit code 1
```

I still get the same error message while the empty project runs freerasp.

Is there another difference I should try to detect?

**Comment by talsec-app** [comment] 2022-01-27 10:15
Hello.
We are trying very hard to replicate, identify and solve problem. We found some possible solutions to your problem.
Troubleshooting:
- Uninstall application from device and let Flutter install it again (`flutter run`)
- Run `flutter clean` and then re-run (**not** hot restart) application
- Try to remove other Flutter packages from dependencies and run project only with freerasp. There could be some compatiblity issues with other packages.

**Comment by lcuis** [comment] 2022-01-27 13:13
Hi @talsec-app ,

Thanks for your help!

I just tried the following:
- `flutter clean`
- uninstall from device
- `flutter run`

I still get the same error message.

```
E/MethodChannel#plugins.aheaditec.com/config(29703): Failed to handle method call
E/MethodChannel#plugins.aheaditec.com/config(29703): java.lang.NullPointerException
E/MethodChannel#plugins.aheaditec.com/config(29703):    at com.aheaditec.freerasp.FreeraspPlugin.onMethodCall(FreeraspPlugin.kt:29)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at android.app.ActivityThread.main(ActivityThread.java:8595)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#plugins.aheaditec.com/config(29703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Activating Dart DevTools...                                        10.3s
E/flutter (29703): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (29703):      at com.aheaditec.freerasp.FreeraspPlugin.onMethodCall(FreeraspPlugin.kt:29)
E/flutter (29703):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (29703):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (29703):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (29703):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (29703):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (29703):      at android.os.Looper.loop(Looper.java:206)
E/flutter (29703):      at android.app.ActivityThread.main(ActivityThread.java:8595)
E/flutter (29703):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (29703):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (29703):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (29703): )
E/flutter (29703): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (29703): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (29703): <asynchronous suspension>
E/flutter (29703): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:35)
E/flutter (29703): <asynchronous suspension>
E/flutter (29703): 

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
plugins.aheaditec.com/events:
MissingPluginException(No implementation found for method listen on channel
plugins.aheaditec.com/events)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

I will now try removing the plugins one by one.

**Comment by lcuis** [comment] 2022-01-28 22:42
I finally got rid of all the plugins in my project and I still have the same issue.

Is there something else I can do?

**Comment by lcuis** [comment] 2022-01-29 00:17
I got it to work with a non-functional project.
I had to migrate to null-safety with a `sdk: '>=2.12.0 <3.0.0'` line in `pubspec.yaml`. This somehow forced me to define the `expectedSigningCertificateHash`.

I rolled back to before the null-safety migration and the plugins removal, I added the `expectedSigningCertificateHash` parameter and the project runs as expected.

So, my issue was the missing `expectedSigningCertificateHash` parameter.

**Comment by talsec-app** [comment] 2022-01-31 09:48
Hello.

Thank you for your work. We can confirm that issue is caused by this problem. Our plugin was written when null-safety was out for quite a long time. Our constructor uses `required` keyword which does not allow null values and also makes named parameters mandatory. Older SDKs will not recognize this though.

**expectedSigningHash, expectedPackageName (in AndroidConfig) and appBundleId, appTeamId (for IOSConfig) are mandatory.**

This issue will be fixed in next release.

We would like to ask @Pacane and @urbanjagodic if this solved their issue or the issue persists.

Thank you for your cooperation.
Talsec Team

**Closed** 2022-02-15 14:44 UTC

**Comment by Developer1414** [comment] 2023-05-12 19:29
@talsec-app When I start the application, I get an error like this and the application crashes:

`W/AudioCapabilities( 4638): Unsupported mime audio/x-ms-wma
W/VideoCapabilities( 4638): Unsupported mime video/divx
W/VideoCapabilities( 4638): Unsupported mime video/x-flv
W/VideoCapabilities( 4638): Unsupported mime video/vnd.rn-realvideo
W/VideoCapabilities( 4638): Unsupported mime video/vc1
W/VideoCapabilities( 4638): Unsupported mime video/ffmpeg
W/VideoCapabilities( 4638): Unsupported mime video/x-ms-wmv
E/AndroidRuntime( 4638): FATAL EXCEPTION: main
E/AndroidRuntime( 4638): Process: com.revens.mini.casino, PID: 4638
E/AndroidRuntime( 4638): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.revens.mini.casino-2/base.apk"],nativeLibraryDirectories=[/data/app/com.revens.mini.casino-2/lib/x86, /data/app/com.revens.mini.casino-2/base.apk!/lib/x86, /system/lib, /vendor/lib, /data/downloads, /data/priv-downloads]]] couldn't find "libpolarssl.so"
E/AndroidRuntime( 4638): 	at java.lang.Runtime.loadLibrary0(Runtime.java:994)
E/AndroidRuntime( 4638): 	at java.lang.System.loadLibrary(System.java:1562)
E/AndroidRuntime( 4638): 	at com.aheaditec.talsec.security.z1.<clinit>(SourceFile:1)
E/AndroidRuntime( 4638): 	at com.aheaditec.talsec.security.y1.<init>(SourceFile:5)
E/AndroidRuntime( 4638): 	at com.aheaditec.talsec.security.y1.a(SourceFile:4)
E/AndroidRuntime( 4638): 	at com.aheaditec.talsec_security.security.api.Talsec.start(SourceFile:1)
E/AndroidRuntime( 4638): 	at com.aheaditec.freerasp.TalsecApp.init(TalsecApp.kt:27)
E/AndroidRuntime( 4638): 	at com.aheaditec.freerasp.MethodCallHandlerImpl.init(MethodCallHandlerImpl.kt:54)
E/AndroidRuntime( 4638): 	at com.aheaditec.freerasp.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:21)
E/AndroidRuntime( 4638): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 4638): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 4638): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 4638): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/AndroidRuntime( 4638): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 4638): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4638): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 4638): 	at android.app.ActivityThread.main(ActivityThread.java:6138)
E/AndroidRuntime( 4638): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4638): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
E/AndroidRuntime( 4638): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
I/Process ( 4638): Sending signal. PID: 4638 SIG: 9
Lost connection to device.
Exited (sigterm)`

**Comment by Developer1414** [comment] 2023-05-12 19:31
@talsec-app My code, executed in initState, looks like this:

`Future<void> initSecurityState() async {
    TalsecConfig config = TalsecConfig(
      androidConfig: AndroidConfig(
        expectedPackageName: 'com.revens.mini.casino',
        expectedSigningCertificateHashes: [
          'SmdUsJDwb6ZlkQS+B2iQKpRVeQsKsIgbO5uEA4tkiJU='
        ],
      ),
      watcherMail: 'develope14000@gmail.com',
    );

    TalsecCallback callback = TalsecCallback(
        androidCallback: AndroidCallback(
      onRootDetected: () => print('root'),
      onEmulatorDetected: () => print('emulator'),
      onHookDetected: () => print('hook'),
      onTamperDetected: () => print('tamper'),
      onDeviceBindingDetected: () => print('device binding'),
      onUntrustedInstallationDetected: () => print('untrusted install'),
    ));

    TalsecApp app = TalsecApp(
      config: config,
      callback: callback,
    );

    app.start();
  }`

**Comment by msikyna** [comment] 2023-05-15 07:50
Hello @Developer1414 ,

the app is crashing because there is a missing x86 native module.
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.revens.mini.casino-2/base.apk"],nativeLibraryDirectories=[/data/app/com.revens.mini.casino-2/lib/x86, /data/app/com.revens.mini.casino-2/base.apk!/lib/x86`

Flutter officially supports only some ABIs in the release mode, and platform x86 is not included (more information here - [https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures](https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures)). Because of that, we decided to distribute our library also without the x86 support. 

This issue should only affect the development process (as the release mode does not support the x86 platform anyway). If you are running the application on Emulator, we recommend downloading an Android image with supported ABI. If you have any questions, please let us know.

Best regards,
Talsec team
