### ISSUE TITLE
Crash in Android 8.0.0

### ISSUE THREAD

**Issue by matehat** [talsec/Free-RASP-Flutter#7] opened 2021-12-20 15:00 UTC
We have seen this from a Android 8.0.0 device in the while, apparently causing a complete crash of the app.

```
OS Version: Android 8.0.0 (R16NW.A520WVLSECTJ1)
Report Version: 104

Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   libc.so                         0x7ee620f758        pthread_mutex_lock
1   libc.so                         0x7ee61c6b4c        readdir
2   split_config.arm64_v8a.apk      0x7ebac4eccc        idr
3   split_config.arm64_v8a.apk      0x7ebac4fb84        Java_com_aheaditec_talsec_1security_security_Natives_a
4   base.odex                       0x7ec50fcdfc        oatexec
```

**Comment by talsec-app** [comment] 2021-12-21 14:03
We couldn't reproduce this issue. How often do you encounter this issue? Each startup, once in a while, etc.? How many devices are affected by this issue? 
We have experienced a similar issue which should be fixed in the latest version. Could you specify which version do you use?

**Comment by talsec-app** [comment] 2022-02-15 14:40
Hello.
We have successfully replicated given issue on the older version of freeRASP. Issue should be fixed in the newest version of freeRASP.
Talsec Team

**Closed by talsec-app** 2022-02-15 14:40 UTC
