### ISSUE TITLE
Build error : The generated assembly code contains unobfuscated DWARF debugging information

### ISSUE THREAD

**Issue by fabienbranchel** [talsec/Free-RASP-Flutter#62] opened 2023-05-15 12:54 UTC
**Describe the bug**
When I try to do CI build (Bitrise), I have this error message since I use freerasp :

> Running pod install...                                          
>     3.4s
> Running Xcode build...                                          
> Xcode build done.                                           143.5s
> Failed to build iOS app
> Error (Xcode): Warning: The generated assembly code contains unobfuscated DWARF debugging information.

However, local run and local iOS build is fine.

**To Reproduce**
Well, I'm not sure... Try building on Bitrise or an other CI ?

**Expected behavior**
Build ok.

**Screenshots**
N/A

**Please complete the following information:**
- Stack and machine type on Bitrise : Xcode 14.3.x, on macOS 13.2 (Ventura) Intel Medium
- My personal Mac : Xcode 14.3.x, on macOS 13.3.1 (a) (Ventura) Intel Core i5
 - Device: iPhone SE (3rd generation) simulator, or same real device
 - OS version: iOS 16.4
 - Version of freeRASP: 4.0.0

**Additional context**
N/A

**Comment by msikyna** [comment] 2023-05-16 13:48
Hello @fabienbranchel ,
does the issue still persist with the new version? It has been released recently: `5.0.0`.

Kind regards,
Talsec team

**Comment by fabienbranchel** [comment] 2023-05-24 13:26
Hello @msikyna,

The issue still persist with the last 5.0.3 version released.

**Comment by yardexx** [comment] 2023-05-29 11:59
Hello.

Unfortunately, I am unable to reproduce the issue. Is that **full** error message you get from Bitrise? Warning shouldn't shut down whole compilation process.

Kind regards,
Jaroslav from Talsec Team

**Comment by yardexx** [comment] 2023-05-30 07:41
Seems like there is an issue with some Flutter build script. I've managed to run Bitrise CI with freeRASP just fine. Could you try to clear Bitrise (xcode) cache?

**Comment by yardexx** [comment] 2023-06-26 12:47
Apologies but I didn't manage to reproduce the issue :/

Could you provide list of other plugins you use? There could be some sort of compatibility issue.

**Comment by msikyna** [comment] 2023-07-19 06:03
Hello @fabienbranchel ,
did you manage to solve the issue? Could you provide the list of plugins as @yardexx asked? Thank you!

Kind regards,
Talsec team

**Comment by fabienbranchel** [comment] 2023-07-19 11:53
Hello,
I had a production build to do at this time, so I simply removed all freerasp related things to get things done in time. 
I tried few days ago to use freerasp again, and all is working fine now.

**Comment by yardexx** [comment] 2023-08-04 10:46
Hello.

As this issue doesn't persist, I am closing it. However, we'll keep an eye on it. If the issue reoccurs, don't hesitate to reopen it.

**Closed by yardexx** 2023-08-04 10:46 UTC
Labels: bug, waiting for response
